name: Build Android
on: push

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
      - name: Setup Android SDK
        uses: amyu/setup-android@v4
        with:
          cache-disabled: true
          sdk-version: 34
          build-tools-version: 35.0.0
          cmake-version: 3.22.1
          ndk-version: 26.3.11579264
          generate-job-summary: false
      - name: Setup Flutter Version
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
        with:
          path: ".fvmrc"
      - name: Install Flutter Version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
      - name: Build APK
        run: flutter build apk --no-tree-shake-icons
      - name: Check Output File
        run: |
          cd build/app/outputs/flutter-apk/
          ls
      - name: Echo If Success
        if: success()
        run: echo "Build Complete"
      - name: Echo If Fail
        if: failure()
        run: echo "Build Fail"
